### ISSUE TITLE
Slider in ScrollView on iOS

### ISSUE THREAD

**Issue by zell180** [jgillick/react-native-a11y-slider#1]
hello i use expo and i ran into this problem on ios: if i insert a double slider in a scrollview the slider becomes unusable because while i try to move one of its indicators the scroll view moves and the component becomes unusable

**Comment by jgillick** [comment]
Is it a horizontal scrollview? You can use `onSlidingStart` and `onSlidingComplete` to disable the ScrollView while the markers are being dragged.

If this doesn't work, can you provide an example repo or [snack](https://snack.expo.dev/) to help demonstrate the bug you're reporting?

**Comment by zell180** [comment]
We are really gratefull to you! great slider!
