### ISSUE TITLE
Three colors in two thumbs slider

### ISSUE THREAD

**Issue by manarfalah** [jgillick/react-native-a11y-slider#2]
How can Achieve three colors in two thumbs slider like below?

it Allows me to make two colors only one colors on left and right and one on the middle.
![Screenshot 2023-03-16 at 10 07 27](https://user-images.githubusercontent.com/6088761/225561209-d4501cb6-2d46-42a8-b7fe-3598b812e7c2.png)

help please !

**Comment by jgillick** [comment]
Currently, only 2 colors are supported. This shouldn't be too hard to add to the library if you want to submit a PR.
