### ISSUE TITLE
Narrator reads zero

### ISSUE THREAD

**Issue by bahri-dev** [jgillick/react-native-a11y-slider#3]
In order to check accessibility of this Slider, I tried to open windows/narrator. Narrator always reads "zero percent". How can fix the issue?

**Comment by jgillick** [comment]
Can you list the steps to reproduce? Was this on a physical device or an emulator? iOS or Android?

**Comment by jgillick** [comment]
Closing this due to lack of steps to reproduce. Feel free to reopen, if necessary.
