### ISSUE TITLE
Slider thumb falling outside of component width for max value

### ISSUE THREAD

**Issue by skolasbn** [jgillick/react-native-a11y-slider#5]
When I set a small range, like 1-10, the max slider value falls outside the range area. It seems to work fine for large numbers like 1-100. Please advise

**Comment by jgillick** [comment]
Can you elaborate? Are you saying that the slider itself visually goes beyond the slide track? Can you provide a screenshot?

**Comment by jgillick** [comment]
@skolasbn  Thanks for reporting this. I believe I've fixed it in version 1.3.0.

**Comment by jgillick** [comment]
Closing this issue as fixed. Feel free to re-open, or open another, if you're still experiencing this.
