### ISSUE TITLE
Issue with onChange and Label text

### ISSUE THREAD

**Issue by kirk-keen** [jgillick/react-native-a11y-slider#6]
When I use the onChange, the Label will not update! and UI goes wrong!
`<Slider
                labelComponent={RSliderLabel}
                sliderStart={sliderStart}
                sliderStop={sliderStop}
                min={0}
                max={1000000}
                increment={1000}
                values={[1000, 1000000]}
                markerComponent={RSliderThumb}
                labelStyle={{
                    backgroundColor: RColors.c1_50,
                    borderRadius: 5,
                }}
                labelTextStyle={{
                    color: RColors.c1,
                    fontSize: RStyles.h5,
                    fontWeight: '500',
                }}
                selectedTrackStyle={{ borderColor: RColors.c1, borderWidth: 4, bottom: -2 }}
                onChange={(values) => {
                    RLog("change", values)
                    setFilter((prev) => ({ ...prev, price: values }))
                }}
            />}`
            
<img width="281" alt="Screen Shot 2023-10-22 at 13 09 31" src="https://github.com/jgillick/react-native-a11y-slider/assets/123240851/1fa32647-c12d-4ae0-b2ed-cbaccd7fca15">

**Comment by kirk-keen** [comment]
This is without onChange prop

<img width="278" alt="Screen Shot 2023-10-22 at 13 10 50" src="https://github.com/jgillick/react-native-a11y-slider/assets/123240851/416644c7-fce0-480f-bafa-fd390242f20c">

**Comment by jgillick** [comment]
(gentle tip suggestion: if you format your code using [fenced blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) it's easier to read & troubleshoot)

```jsx
<Slider 
  labelComponent={RSliderLabel} 
  sliderStart={sliderStart} 
  sliderStop={sliderStop} 
  min={0} 
  max={1000000} 
  increment={1000} 
  values={[1000, 1000000]} 
  markerComponent={RSliderThumb} 
  labelStyle={{ backgroundColor: RColors.c1_50, borderRadius: 5, }} labelTextStyle={{ color: RColors.c1, fontSize: RStyles.h5, fontWeight: '500', }} 
  selectedTrackStyle={{ borderColor: RColors.c1, borderWidth: 4, bottom: -2 }} 
  onChange={(values) => { 
    RLog("change", values) 
    setFilter((prev) => ({ ...prev, price: values })) 
  }} />
```

Can you define the issue a bit more? Are the labels/markers draggable or are they stuck in place? What does the `setFilter` function do? You have defined a custom label component, can you include that here too? What if you remove the custom label component? 

Is it possible to create a minimal reproduction repository that I can use to see the issue you're reporting? You can fork this repo and update the example app.

**Comment by kirk-keen** [comment]
Hey Jeremy,

Thank you for your response.
In the case of your questions:
Can you define the issue a bit more? 
Are the labels/markers draggable or are they stuck in place? 
ANS: The Lable is draggable with the thumb.

What does the setFilter function do? 
ANS: it just saves the current value, then I will send the values of the form to another screen.

You have defined a custom label component, can you include that here too? 
ANS: I just made a copy of the default Lable component, with a simple change to show the value as currency. check the image.

What if you remove the custom label component?
ANS: Nothing changed, the issue just appeared when I set the onChange. :(

<img width="692" alt="Screen Shot 2023-10-26 at 10 39 24" src="https://github.com/jgillick/react-native-a11y-slider/assets/123240851/1809e512-d334-4fe8-8a88-5c0a5f5c744a">

**Comment by jgillick** [comment]
I still cannot reproduce your issue, but I've updated the lib (v1.3.2) to make customizing the label value easier. Now you can import the Label component and simply use it inside your custom label, without having to rebuild the label entirely. See the [example app code](https://github.com/jgillick/react-native-a11y-slider/blob/main/example/App.tsx#L148-L163)

For example:

```tsx
import Slider, { SliderLabel, LabelProps } from "react-native-a11y-slider";

function CustomLabel(props: LabelProps) {
  /**
   * Format label value as currency
   */
  const position = useMemo(() => {
    if (typeof props.position.value === "number") {
      return {
        ...props.position,
        value: `$${props.position.value}`,
      };
    }
    return props.position;
  }, [props.position]);

  return <SliderLabel {...props} position={position} />;
}
```

When I implement it with the onChange handler, it still works as expected for me:

```tsx
<Slider
  min={1}
  max={100}
  values={[10, 50]}
  onSlidingStart={sliderStart}
  onSlidingComplete={sliderStop}
  labelComponent={CustomLabel}
  onChange={(values) => {
    console.log("change", values);
  }}
/>
```

Can you try to reproduce the bug in the example project: 
https://github.com/jgillick/react-native-a11y-slider/tree/main/example
